apiVersion: v1
kind: Service
metadata:
  name: amf-open5gs-sctp
  labels:
    epc-mode: amf
spec:
  type: NodePort
  selector:
    epc-mode: amf
  ports:
    - name: ngap
      protocol: SCTP
      port: 38412
      targetPort: 38412
      nodePort: 30412
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-amf
  labels:
    epc-mode: amf
    open5gs.io/metrics: {{ .Values.metrics.enabled | quote }}
  {{- if .Values.metrics.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.metrics.port }}"
    prometheus.io/path: "/metrics"
  {{- end }}
spec:
  selector:
    epc-mode: amf
  ports:
    - name: sbi
      protocol: TCP
      port: 7777
      targetPort: 7777
    {{- if .Values.metrics.enabled }}
    - name: metrics
      protocol: TCP
      port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
    {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-amf-deployment
  labels:
    epc-mode: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: amf
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        {{- if .Values.metrics.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.metrics.port }}"
        prometheus.io/path: "/metrics"
        {{- end }}
      labels:
        epc-mode: amf
    spec:
      containers:
        - name: amf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-amfd", "-c", "/open5gs/config-map/amf.yaml"]
          ports:
            - name: sbi
              containerPort: 7777
            - name: ngap
              containerPort: 38412
              protocol: SCTP
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
            {{- end }}
          volumeMounts:
          - name: open5gs-amf-config
            mountPath: /open5gs/config-map/amf.yaml
            subPath: "amf.yaml"
      volumes:
        - name: open5gs-amf-config
          configMap:
            name: open5gs-amf-config
