apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-ausf-config
  labels:
    epc-mode: ausf
data:
  ausf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/ausf.log
    global:
      max:
        ue: 1024
    ausf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
            advertise: open5gs-ausf
        client:
          nrf:
            - uri: http://open5gs-nrf:7777
