apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nrf-config
  labels:
    epc-mode: nrf
data:
  nrf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/nrf.log
    global:
      max:
        ue: 1024
    nrf:
      serving:
        - plmn_id:
            mcc: {{ .Values.amf.mcc }}
            mnc: {{ .Values.amf.mnc }}
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
            advertise: open5gs-nrf
