apiVersion: v1
kind: Service
metadata:
  name: open5gs-smf
  labels:
    epc-mode: smf
    open5gs.io/metrics: {{ .Values.metrics.enabled | quote }}
  {{- if .Values.metrics.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.metrics.port }}"
    prometheus.io/path: "/metrics"
  {{- end }}
spec:
  selector:
    epc-mode: smf
  ports:
    - name: sbi
      protocol: TCP
      port: 7777
      targetPort: 7777
    {{- if .Values.metrics.enabled }}
    - name: metrics
      protocol: TCP
      port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
    {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-smf-deployment
  labels:
    epc-mode: smf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: smf
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        {{- if .Values.metrics.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.metrics.port }}"
        prometheus.io/path: "/metrics"
        {{- end }}
      labels:
        epc-mode: smf
    spec:
      containers:
      - name: smf
        image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
        imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
        command: ["open5gs-smfd", "-c", "/open5gs/config-map/smf.yaml"]
        ports:
          - name: sbi
            containerPort: 7777
          {{- if .Values.metrics.enabled }}
          - name: metrics
            containerPort: {{ .Values.metrics.port }}
          {{- end }}
        volumeMounts:
          - name: open5gs-smf-config
            mountPath: /open5gs/config-map/smf.yaml
            subPath: "smf.yaml"
      volumes:
        - name: open5gs-smf-config
          configMap:
            name: open5gs-smf-config
