apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udm-config
  labels:
    epc-mode: udm
data:
  udm.yaml: |
    logger:
      file:
        path: /var/log/open5gs/udm.log
    global:
      max:
        ue: 1024
    udm:
      hnet:
        - id: 1
          scheme: 1
          key: /etc/open5gs/hnet/curve25519-1.key
        - id: 2
          scheme: 2
          key: /etc/open5gs/hnet/secp256r1-2.key
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
            advertise: open5gs-udm
        client:
          nrf:
            - uri: http://open5gs-nrf:7777
