apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udr-config
  labels:
    epc-mode: udr
data:
  udr.yaml: |
    db_uri: mongodb://mongodb-svc/open5gs
    logger:
      file:
        path: /var/log/open5gs/udr.log
    global:
      max:
        ue: 1024
    udr:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
            advertise: open5gs-udr
        client:
          nrf:
            - uri: http://open5gs-nrf:7777
